#
# █░█ █▄█ █▀█ █▀█ █░░ █▀█ █▀▀ █▄▀
# █▀█ ░█░ █▀▀ █▀▄ █▄▄ █▄█ █▄▄ █░█
#

source = ./catppuccin-frappe.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = SF Pro Display
$fontBold = SF Pro Display Bold


general {
    hide_cursor = true,
    #ignore_empty_input = false,
	#immediate_render = false,
	text_trim = false,
    #fractional_scaling = 2,
    #screencopy_mode = 0,
    #fail_timeout = 2000,
}


authentication {
    #pam:enable = true
    #pam:module = hyprlock
    #fingerprint:enabled = false
    #fingerprint:ready_message = (Scan fingerprint to unlock)
    #fingerprint:present_message = Scanning fingerprint
    #fingerprint:retry_delay = 250
}

animations {
    #enabled = true
}


background {
    monitor =
    path = ~/.config/wallpapers/space.jpg
    blur_passes = 0
    color = $base
}


# Time
label {
    monitor =
    text = cmd[update:60] echo "$(date +"%I:%M")"
    color = $text
    font_size = 90
    font_family = $fontBold
    position = 0, 350
    halign = center
    valign = center
}


# Date as yyyy-mm-dd (iso8601)
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date -I)"
    color = $text
    font_size = 22
    font_family = $fontBold
    position = 0, 330
    halign = center
    valign = center
}


# Fingerprint
label {
    monitor =
    text = $FPRINTPROMPT
    color = $text
    font_size = 14
    font_family = $font
    position = 0, -107
    halign = center
    valign = center
}


# User avatar
image {
    monitor =
    path = ~/.face.png
    size = 100
    border_size = 2
    border_color = $accent
    position = 0, 75
    halign = center
    valign = center
}


# Password input field
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $accent
    inner_color = $surface0
    font = $font
    font_color = $text
    fade_on_empty = false
    placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
    hide_input = false
    check_color = $accent
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $yellow
    position = 0, -47
    halign = center
    valign = center
}
